HF_KEY='Enter a Huggingface Access Key (it will be something like hf_..nOIw) from your profile on huggingface.co.  If you dont have one yet create one with name of HF_KEY'
API_KEY='Enter a Huggingface Access Key (it will be something like hf_..nOIw) from your profile on huggingface.co.  If you dont have one yet create one with name of API_KEY'
